#!/bin/bash
g++ -Wall -Wextra -Wconversion -static -DONLINE_JUDGE -Wl,--stack=268435456 -O2 -std=c++20 $1
# g++ -static -DONLINE_JUDGE -Wl,--stack=268435456 -O2 -std=c++17 $1
# g++ -o %run_name%.exe 2>compilation.log

# C:\\Programs\\gcc11-64-winlibs\\bin\\g++.exe
# E:\\mingw32\\bin\\g++.exe
./a < input